version: '3.9'
services:
  postgres:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hwg_lafontn
    container_name: lafontn-bdd
    ports:
      - '3306:3306'
  nginx:
    depends_on:
      - api
      - app
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./hwg-lafontn/nginx
    container_name: server-lafontn
    ports:
      - "3006:80"
    volumes:
      - ./hwg-lafontn/nginx/default.conf:/etc/nginx/conf.d/default.conf
  api:
    build:
      dockerfile: Dockerfile.dev
      context: './hwg-api'
    volumes:
      - /app/node_modules
      - ./hwg-api:/app
    environment:
      - DB_USER=root
      - DB_HOST=mysql
      - DB_NAME=hwg_lafontn
      - DB_PASSWORD=root
      - DB_PORT=3306
    container_name: lafontn-api
    ports:
      - '8081:8080'
  app:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: './hwg-lafontn'
    volumes:
      - /app/node_modules
      - ./hwg-lafontn:/app
    container_name: lafontn-front
    ports:
      - '3000:3000'

# To go to production, comment on the lines above and uncomment the lines below

# version: '3.9'
# name: hwg-lafontn-prod
# services:
#   postgres:
#     image: 'postgres:latest'
#     environment:
#       - POSTGRES_PASSWORD=postgres_password
#     container_name: lafontn-bdd-prod
#     ports:
#       - '5432:5432'
#   api:
#     build:
#       dockerfile: Dockerfile
#       context: './hwg-api'
#     volumes:
#       - /app/node_modules
#       - ./hwg-api:/app
#     environment:
#       - PGUSER=postgres
#       - PGHOST=postgres
#       - PGDATABASE=hwg-lafontn
#       - PGPASSWORD=postgres_password
#       - PGPORT=5432
#     container_name: lafontn-api-prod
#     ports:
#       - '8080:8080'
#   app:
#     stdin_open: true
#     build:
#       dockerfile: Dockerfile
#       context: './hwg-lafontn'
#     volumes:
#       - /app/node_modules
#       - ./hwg-lafontn:/app
#     container_name: lafontn-front-prod
#     ports:
#       - '80:80'